// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUet5LMqC0Lai0hzfElmYfpVMMfyI1eGI',
    appId: '1:702931477948:android:0e7d139057f76496cdf7b9',
    messagingSenderId: '702931477948',
    projectId: 'flutter-push-3b5e5',
    storageBucket: 'flutter-push-3b5e5.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaPifI0OOmYtCnKBPodbRLy6fz1n0Y6c',
    appId: '1:702931477948:web:a78ede427de63380cdf7b9',
    messagingSenderId: '702931477948',
    projectId: 'flutter-push-3b5e5',
    authDomain: 'flutter-push-3b5e5.firebaseapp.com',
    storageBucket: 'flutter-push-3b5e5.appspot.com',
    measurementId: 'G-SGYY62E79Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH84L9a8NUglNc2TmwxHi3CXhiZ7tW59E',
    appId: '1:702931477948:ios:d44307a970a5bc7ccdf7b9',
    messagingSenderId: '702931477948',
    projectId: 'flutter-push-3b5e5',
    storageBucket: 'flutter-push-3b5e5.appspot.com',
    iosBundleId: 'com.example.flutterPush',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH84L9a8NUglNc2TmwxHi3CXhiZ7tW59E',
    appId: '1:702931477948:ios:d44307a970a5bc7ccdf7b9',
    messagingSenderId: '702931477948',
    projectId: 'flutter-push-3b5e5',
    storageBucket: 'flutter-push-3b5e5.appspot.com',
    iosBundleId: 'com.example.flutterPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMaPifI0OOmYtCnKBPodbRLy6fz1n0Y6c',
    appId: '1:702931477948:web:c7c4cef801e8db5fcdf7b9',
    messagingSenderId: '702931477948',
    projectId: 'flutter-push-3b5e5',
    authDomain: 'flutter-push-3b5e5.firebaseapp.com',
    storageBucket: 'flutter-push-3b5e5.appspot.com',
    measurementId: 'G-XGX0XEWTB1',
  );

}